server:
  port: 8003

spring:
  application:
    name: hlpay-provider-service #CLOUD-PAYMENT-SERVICE
  zipkin:
    base-url: http://localhost:9411
    sleuth:
      sampler:
      probability: 1 #采样率值介于0到1之间，1则表示全部采集

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 1234567

eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:7001/eureka #,http://eureka7002.com:7002/eureka  #集群版
  instance:
    instance-id: hlpay-provider8001
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 60

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.hlwl.pay.entities    # 所有Entity别名类所在包