activezmy: dev
alipaylist:
  list:
    configs:
      - serverurl: 'https://openapi.alipay.com/gateway.do'
        appid: '2017090608583349'
        privatekey: 'MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCb1++4puS1HDNFAnDYm3j7PpzjR7T2hCp8TCcR3dZeQ0RT6qP9GYIhdRJo1mviz/YqJ5tt5xYIKASmdh7uL5sCSjBOIDPOjSTjoHeiTucyiEMQ4go06Z5fwMjzvMIeM53GxdQYjqsGdRpf8F1z3zAUytB2JsRIPP5NbCaoTieKOAetHXnkpxyZSWwwmPUukrqRb3eiU+zxw+B0GjlYBAVVjaUmg04DdKxkqq5lhuWI4w7Em6nWDmnnNOssPT0KqMbh99XpYgzNVmE5GvYU6FimgGlPawggUv6EKf0t5zU+gPFnBadkTP2YevVbIqm+JAeGsfh0mKNtOHLe9HkagOk5AgMBAAECggEANyxRwEvFuKDNPedJUEZqpHhcTtK6LHRKHktPobGqDSE/dX4ipJ59RZ8O73LKKzh47B+tlVE0qZqRWuWCucy80ii1xVL9RGkP4E6VTC8nBura44VDG8yBt2CnRDNVfh/EAfVTy4Xm4pheyAxu6XDgstvCxbGf1/tQBNT/MqLIuNPgf4p6B1L8EDRmP09Zslbq0TbN5P1EaPmylEUE6/th+Sprp24aUQRiiL9HPxer4nsTEWaB2i8yA1k13/on4AL7t255Mw9/EJFZuz0hHRv+fxtUF6E8XZ+/ZfC5pFLDLGemAHwnSJFj3zxcRFW9nEC5fjvc/l0yXdsyW5Dza3kuyQKBgQD4mal9BzkYI9/ixUOIQsvTzKRxr4ToJZSMzwUzmIFDo6PA2sII3NVFDubLaPE5iBElVMZkFJ+VTh73i1KkpyOSiO0Luzs9KIZROtaLQ3dgk/vvbu2Esgm0lxcc8Dh39VRVyrOz1xBv7FzSJ41ljwGn5aQFmD/AdUMgu7yDYvHzcwKBgQCge3dps7CUFH0VTjtPHKBtAE/mG6RZALmxL/+royEQ9C07PeZHhZHLEM7EC2dR/W7hPqZ5+w9/okCMt32bkIcVS32p966y3h3HhLwEUGGBHmQ5Di0weKJtrZuFEgHkxeNihYuSLxGmcl2bnSE3XPxmINoZf2YNdUguKOtl9629owKBgBy5/OjSrdlJQ/S7YLtdJJp72kC8zHna5diDj5FPvRgoz6JYZPWLNyW8vBSjMsS4IWsT6bzk2S/ykAeA1PLr0WN8aQ/i+cxuY179ko8TI7dIQmN/iPi9bfutPeF9LLlH4w/q1WshneehA3TRVzh2FvXkxlhTKIK/yhr9NqJkC5tbAoGBAIT35+gn323CUCWADXouMOo/sPPrAVBRXopmR8PRxQsEFhoY3p1yGWuUgI1FGZWAlAeDXnKBR8UsDanKOwPTS2mkg/l5ZEGF8kynORWl+DQAl3ACxAR+X67agppOYk1IfW/bUNqNr2UnK1JNbgEuRV7lZ3Bq84bBH05Hz0tMXaNbAoGAIUCwIHB5zSSwS3f6cm8GJNP4lybBwIe4xh4Z9e/FbASYH+4x+9mRskyAACBvLQmoXM7HZjuCALlebne88S6yWsfaaTdD+B4pJ+QS271w5Q3PuMNCOM+Nzd5eXD6ii5NYiRWsqq7e45EHD8fOk5ntjLyGX/Ik733FPBtyINXZB2E='
        format: 'json'
        charset: 'UTF-8'
        alipaypublickey: 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAu+dmxZpzpgzMGAs+YR28yE+01HDe+yEH9LAjBtloSSRNOG1c3uBiBYV648pXgecfDEcDFMZs1GntAiJnuBw8ux3vGi57uBNUC2uoyRuxHs2DfGsTj381OFDYlwU4pr7lKvvFX3v0x6Ul6TV9is6IRk2yKczqVhN86JjthgmYuS3SjGvUFixwffHpIGrQhVosfXiF5WZq+lUgWa99f3UCNNF88+jiQQ2hr7m+5EQQo0pYxpuXugBcXfJAu27vNWs2FHzM9j2GocNXb+/SPYV71bDbNvOK4XuvygyFk99oL4gZILotnn0N+sNJUFOkM5nhw1UciE7f26nf5Fw0Z/CO8QIDAQAB'
        signtype: 'RSA2'
      - serverurl: 'https://openapi.alipay.com/gateway.do'
        appid: '2016051101387917'
        privatekey: 'MIICeAIBADANBgkqhkiG9w0BAQEFAASCAmIwggJeAgEAAoGBAO0hr9YbqKq0hZpdLgiBSGyagWiqillwk+udWNy+OJQyDtORBR41028jYhED4DRSfg5iaC3I8e9DtbQpbMLgWa/bkdknAMVNUoNJesQ2TQlFnhgqRUv02U5zMGI90TCafGEi1di6wz7MIYv54G/otYmmUGWRT3vzdRz0XB72hcPhAgMBAAECgYA/JmJ6ZYFEfLC7zCbPMwbDjV37LreLXBS4gX3Bw5KzvKUAKLWxNupoxYZ/O4YAyRsy33gZAVOUwXZpVULWnwKi9F1Xt7EMKI1HvCZE8+xs7zyWSNsQzrorPvKZJGQf9wCHxjjzq9KAtPZuHHsPiiPEGxanDP5LtKhgjEzeeTJ6cQJBAPhR2g4k/QeEZpfNPYcAJjxNh2o6cTmTyOBYaHTMFqsHiVqzZC//ovfgLFb14Sprrnk7PIbetEqFPGpzKCQIlF0CQQD0dz/ezmDER9KZkEqWWDZtwNdPrj7ucs1bXyeFJbe3gWqn3nxGfzCGsGx1Hs35VlXCKB+7WIYFfZxSns5ldnVVAkEAlq1cKk8JdoFBm4U/e2Z8zQSiUbQqtixVrMQYhh689oS5NN87wOBWrCBL52yFd68ljIyEOrZyIfHc6h78UXkfRQJBAMh18J3XRWouKvdZZpAaDae59dSU4W3OHa7LPDDmWNvU94xn2ChGq5gGmyj+9Y97yB7JoBuT33IpKkJljoGMvXECQQCJXVgDwYg2SaMx8LUi3PFnlP6bzqsiSOOK3pEamqW13A+/HlduzEAejOfyK+fMmiHK8rm6I7iQS5UW8LACJf3l'
        format: 'json'
        charset: 'UTF-8'
        alipaypublickey: 'MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDDI6d306Q8fIfCOaTXyiUeJHkrIvYISRcc73s3vF1ZT7XN8RNPwJxo8pWaJMmvyTn9N4HQ632qJBVHf8sxHi/fEsraprwCtzvzQETrNRwVxLO5jVmRGi60j8Ue1efIlzPXV9je9mkjzOmdssymZkh2QhUrCmZYI/FCEa3/cNMW0QIDAQAB'
        signtype: 'RSA'

server:
  port: 1237
  servlet:
    context-path: /YzfPro













